name = "Fastoria"
author = "Alisik"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd62a64df961843225331751bbccd77bab8c9b126c9b90884ab0e97fb62d8343"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
