name = "Fastoria"
author = "Alisik"
version = "1.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b034441726a6f4e98e601f473b7b6dd8f3229a3530be4030975067760eb7453"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
