name = "Fastoria"
author = "Alisik"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8f0d3fe29cb33c62280cc91369d587e723ecacf609eef52b5622ce1d30b8456"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
