name = "Fastoria"
author = "Alisik"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b203fd8f0470505bc6691c70c284490a4add4a51f88ac6f9452afe6bf30e4cd1"

[versions]
fabric = "0.19.3"
minecraft = "26.2-rc-2"
