name = "Fastoria"
author = "Alisik"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aae3a47935f37e76333500c2fcff86d4e0ed6bd1748cbc0f2e1e1824e8d88ea5"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
