name = "Fastoria"
author = "Alisik"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ba9d07b8089563ae8096797f2744e59b524a9fc467f9217ff7ea3dc6c478053"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["26.2-rc.1", "26.2-rc.2"]
