name = "Fastoria"
author = "Alisik"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71a49e2f8166f57f350d128dc54f8af6b661ee1c5eed311bbd192c0254cb550f"

[versions]
fabric = "0.19.3"
minecraft = "26.3-snapshot-3"
