name = "Fastoria"
author = "Alisik"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e361791e56dd9f34adca50124978340fb4545adcb91f3d5e78cb9fe5900ba3e6"

[versions]
fabric = "0.19.3"
minecraft = "26.3-snapshot-3"
