name = "Fastoria"
author = "Alisik"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5eb10bbdf20aaac6e44888bcfe97b608743436b2f4a4b28f544ef91adfe481b"

[versions]
fabric = "0.19.3"
minecraft = "26.3-snapshot-1"
