name = "Fastoria"
author = "Alisik"
version = "1.4.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da2a370c3577c55aca6923e7d840d5935c07fef9c54071aeb7a3c3450774d58b"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.2-rc.1", "26.2-rc.2"]
