name = "Fastoria"
author = "Alisik"
version = "1.4.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7938d0da785ab33f59b956c0115bce57975aeea5759ff07f6e1afb3d16484f3"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.2-rc.1", "26.2-rc.2"]
