name = "Fastoria"
author = "Alisik"
version = "1.4.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0153a8b820892b7995ef81e19d654f22a4cb393a51ba097512429537850c55e"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.2-rc.1", "26.2-rc.2"]
