name = "Fastoria"
author = "Alisik"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e213c1977583a7b91d78638d6817b3f87287b7b255815376f617e7561ae30da"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
