name = "Fastoria"
author = "Alisik"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "819b7610fb4f8358638f3ed3fcee34e7277d4c759d3fa244861009ce9e4e8cd0"

[versions]
fabric = "0.19.3"
minecraft = "26.2-rc-1"
