name = "Fastoria"
author = "Alisik"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "299f5ce00e8f13dacd480620eedea656562fd844db0106e51ac2ed7058b2c1a0"

[versions]
fabric = "0.19.3"
minecraft = "26.2-rc-1"
